/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */

import java.time.LocalDate;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;



public class FormPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form FormPerhitunganHari
     */
    public FormPerhitunganHari() {
        initComponents();
        
        
        setResizable(false);
        setLocationRelativeTo(null);

        
        String[] bulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni",
                      "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
    cmbBulan.removeAllItems();
    for (String b : bulan) {
        cmbBulan.addItem(b);
    }

    // --- set model spinner tahun (integer saja, tidak ada koma) ---
    javax.swing.SpinnerNumberModel modelTahun = new javax.swing.SpinnerNumberModel(2024, 1, 3000, 1);
    spnTahun.setModel(modelTahun);

    // --- agar tampilan spinner selalu integer (tanpa koma/pemisah ribuan) ---
    javax.swing.JSpinner.NumberEditor editor = new javax.swing.JSpinner.NumberEditor(spnTahun, "#");
    spnTahun.setEditor(editor);

    // --- set label awal ---
    lblHasil.setText("Jumlah Hari: -");
    lblInfoHari.setText("Hari pertama & terakhir: -");
    }
    
    private void updateCalendar() {
        try {
        int bulan = cmbBulan.getSelectedIndex(); // Januari = 0
        Object tahunObj = spnTahun.getValue();
        int tahun;

        // Konversi nilai tahun dengan aman
        if (tahunObj instanceof Number) {
            tahun = ((Number) tahunObj).intValue();
        } else {
            tahun = Integer.parseInt(tahunObj.toString().replace(".", ""));
        }

        // Kalau tahun belum valid saat awal run, lewati tanpa pesan error
        if (tahun < 1 || tahun > 3000) {
            return;
        }

        // Ambil tanggal yang sekarang terpilih supaya kita bisa mempertahankan hari jika memungkinkan
        java.util.Date cur = jCalendar2.getDate();
        java.util.Calendar cal = java.util.Calendar.getInstance();

        if (cur != null) {
            cal.setTime(cur);
        } else {
            cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
        }

        // Set year & month sesuai input
        cal.set(java.util.Calendar.YEAR, tahun);
        cal.set(java.util.Calendar.MONTH, bulan);

        // Pastikan hari tidak melebihi jumlah hari pada bulan baru
        int maxDay = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
        int day = Math.min(cal.get(java.util.Calendar.DAY_OF_MONTH), maxDay);
        cal.set(java.util.Calendar.DAY_OF_MONTH, day);

        // Update kalender supaya sinkron
        jCalendar2.setDate(cal.getTime());

    } catch (Exception e) {
        // Jangan munculkan pesan pop-up saat awal program, cukup diam
        System.err.println("Gagal memperbarui kalender: " + e.getMessage());
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelUtama = new javax.swing.JPanel();
        lblBulan = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        spnTahun = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnSelisih = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        lblInfoHari = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jCalendar3 = new com.toedter.calendar.JCalendar();
        lblJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 212, 192));

        panelUtama.setBackground(new java.awt.Color(218, 254, 183));
        panelUtama.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblBulan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblBulan.setText("Pilih Bulan");

        lblTahun.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTahun.setText("Pilih Tahun");

        cmbBulan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        cmbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBulanActionPerformed(evt);
            }
        });

        spnTahun.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        spnTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTahunStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setText("Menggunakan calendar");

        btnHitung.setBackground(new java.awt.Color(243, 238, 178));
        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSelisih.setBackground(new java.awt.Color(255, 212, 73));
        btnSelisih.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnSelisih.setText("Selisih");
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(196, 109, 94));
        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        lblHasil.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblHasil.setText("Jumlah Hari:");

        lblInfoHari.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblInfoHari.setText("Selisih Hari Pertama Dan Terakhir:");

        jCalendar2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCalendar2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar2PropertyChange(evt);
            }
        });

        jCalendar3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTahun)
                                    .addComponent(jLabel6))
                                .addGap(39, 39, 39)
                                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelUtamaLayout.createSequentialGroup()
                                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSelisih, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(111, 111, 111))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(lblInfoHari, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBulan)
                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(34, 34, 34)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahun)
                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelisih))
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar))))
                .addGap(18, 18, 18)
                .addComponent(lblHasil)
                .addGap(40, 40, 40)
                .addComponent(lblInfoHari)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lblJudul.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Aplikasi Perhitungan Angka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
        int tahun = (Integer) spnTahun.getValue();
        int bulanIndex = cmbBulan.getSelectedIndex() + 1; // Januari = 0, jadi +1
        LocalDate tanggal = LocalDate.of(tahun, bulanIndex, 1);

        int jumlahHari = tanggal.lengthOfMonth();
        LocalDate hariPertama = tanggal.withDayOfMonth(1);
        LocalDate hariTerakhir = tanggal.withDayOfMonth(jumlahHari);

        lblHasil.setText("Jumlah Hari: " + jumlahHari + " hari");
        lblInfoHari.setText("Hari pertama: " 
                + hariPertama.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("id", "ID"))
                + " | Hari terakhir: " 
                + hariTerakhir.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("id", "ID")));

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Input tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnHitungActionPerformed

    private void spnTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTahunStateChanged
        // TODO add your handling code here:
        lblHasil.setText("Jumlah Hari: -");
    lblInfoHari.setText("Hari pertama & terakhir: -");
    updateCalendar();
    }//GEN-LAST:event_spnTahunStateChanged

    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        // TODO add your handling code here:
        try {
        // Ambil tanggal langsung dari kedua kalender (tidak mereset/menimpa)
        java.util.Date d1 = jCalendar2.getDate();
        java.util.Date d2 = jCalendar3.getDate();

        if (d1 == null || d2 == null) {
            JOptionPane.showMessageDialog(this, "Pastikan kedua kalender sudah memiliki tanggal terpilih!");
            return;
        }

        // (DEBUG OPTIONAL) - tampilkan nilai mentah agar kita tahu apa yang terbaca program
        // Uncomment baris di bawah ini kalau masih ingin cek nilai saat run
        // JOptionPane.showMessageDialog(this, "debug jCalendar2.getDate() = " + d1 + "\ncal2.getTime() = " + jCalendar2.getCalendar().getTime()
        //     + "\njCalendar3.getDate() = " + d2 + "\ncal3.getTime() = " + jCalendar3.getCalendar().getTime());

        // Konversi java.util.Date ke LocalDate
        java.time.LocalDate tanggal1 = d1.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        java.time.LocalDate tanggal2 = d2.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        // Hitung selisih hari
        long selisih = Math.abs(java.time.temporal.ChronoUnit.DAYS.between(tanggal1, tanggal2));

        // Tampilkan hasil
        JOptionPane.showMessageDialog(this,
            "Selisih antara " + tanggal1 + " dan " + tanggal2 + " adalah " + selisih + " hari.",
            "Hasil Selisih", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan saat menghitung selisih: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnSelisihActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (pilih == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cmbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBulanActionPerformed
        // TODO add your handling code here:
        updateCalendar();
    }//GEN-LAST:event_cmbBulanActionPerformed

    private void jCalendar2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar2PropertyChange
        // TODO add your handling code here:
        if ("calendar".equals(evt.getPropertyName()) && jCalendar2.getDate() != null) {
        // Jalankan setelah UI selesai update agar jCalendar.getDate() konsisten
        javax.swing.SwingUtilities.invokeLater(() -> {
            try {
                java.util.Date dateNow = jCalendar2.getDate();
                if (dateNow != null) {
                    java.util.Calendar cal = java.util.Calendar.getInstance();
                    cal.setTime(dateNow);

                    // pastikan cmbBulan & spnTahun sinkron dengan tampilan kalender
                    cmbBulan.setSelectedIndex(cal.get(java.util.Calendar.MONTH));
                    spnTahun.setValue(cal.get(java.util.Calendar.YEAR));
                }
            } catch (Exception ex) {
                // jangan crash; log/notify singkat
                System.err.println("Error propertyChange jCalendar2: " + ex.getMessage());
            }
        });
    }
    }//GEN-LAST:event_jCalendar2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPerhitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSelisih;
    private javax.swing.JComboBox<String> cmbBulan;
    private com.toedter.calendar.JCalendar jCalendar2;
    private com.toedter.calendar.JCalendar jCalendar3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInfoHari;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JSpinner spnTahun;
    // End of variables declaration//GEN-END:variables
}
